---
- name: Test webserver is responding on port 80.
  uri:
    url: "http://{{ beet_domain }}/"
    status_code: 200

- name: Test webserver is responding on port 443.
  uri:
    url: "https://{{ beet_domain }}/"
    validate_certs: no
    status_code: 200

- name: Test uploadprogress is available.
  shell: >
    php -m
  register: php_modules
  changed_when: false
  failed_when: "'uploadprogress' not in php_modules.stdout"
