---
- hosts: localhost
  connection: local
  become: yes

  vars_files:
    - config/beetbox.config.yml
    - config/project.config.yml
    - config/host.config.yml
    - config/config.yml
    - config/local.config.yml

  tasks:

    - name: Check if roles are installed
      stat: "path={{ beet_role_dir }}/{{ item.name }}"
      with_items: "{{ galaxy_roles }}"
      register: roles_installed

    - name: Install Galaxy roles
      command: >
        ansible-galaxy install {{ item.item.name }} -p {{ beet_role_dir }} --force --ignore-errors
      when: "not {{ item.stat.exists }} and not {{ beet_debug }}"
      with_items: "{{ roles_installed.results }}"

    - name: Update Galaxy roles
      command: >
        ansible-galaxy install {{ item.item.name }} -p {{ beet_role_dir }} --force --ignore-errors
      when: "{{ item.item.force_update }} is defined and not {{ beet_debug }}"
      with_items: "{{ roles_installed.results }}"

    - name: Checkout Galaxy roles
      git:
        repo: "{{ item.item.repo }}"
        dest: "{{ beet_role_dir }}/{{ item.item.name }}"
        accept_hostkey: yes
      when: "not {{ item.stat.exists }} and {{ beet_debug }}"
      with_items: "{{ roles_installed.results }}"
