---
#
# Beetbox VM configuration.
#
# Settigns below related to the Ansible roles from Galaxy.
# Copy any of these settings to the custom config file to override.
#

# Beetbox config.
beet_repo: https://github.com/DrupalMel/beetbox.git
beet_version: "HEAD"
beet_home: /beetbox
beet_role_dir: roles
beet_project: drupal
beet_keep_updated: no
beet_debug: no
beet_domain: "beetbox.local"
beet_root: "/var/beetbox"
beet_web: "{{ beet_root }}/docroot"
beet_ssh_home: "{{ beet_root }}"
beet_site_name: "Beetbox"
beet_mysql_user: beetbox
beet_mysql_password: beetbox
beet_mysql_database: "beetbox_{{ beet_project }}"

# Ansible Galaxy roles.
galaxy_roles:
  - { name: arknoll.selenium }
  - { name: geerlingguy.adminer }
  - { name: geerlingguy.apache }
  - { name: geerlingguy.apache-php-fpm }
  - { name: geerlingguy.composer }
  - { name: geerlingguy.daemonize }
  - { name: geerlingguy.drupal-console }
  - { name: geerlingguy.drush }
  - { name: geerlingguy.firewall }
  - { name: geerlingguy.git }
  - { name: geerlingguy.java }
  - { name: geerlingguy.mailhog }
  - { name: geerlingguy.memcached }
  - { name: geerlingguy.mysql }
  - { name: geerlingguy.nginx }
  - { name: geerlingguy.nodejs }
  - { name: geerlingguy.php }
  - { name: geerlingguy.php-memcached }
  - { name: geerlingguy.php-mysql }
  - { name: geerlingguy.php-pecl }
  - { name: geerlingguy.php-redis }
  - { name: geerlingguy.php-xdebug }
  - { name: geerlingguy.php-xhprof }
  - { name: geerlingguy.pimpmylog }
  - { name: geerlingguy.postfix }
  - { name: geerlingguy.redis }
  - { name: geerlingguy.ruby }
  - { name: geerlingguy.security }
  - { name: geerlingguy.solr }
  - { name: geerlingguy.varnish }
  - { name: heskethm.wp-cli }
  - { name: pwelch.avahi }
  - { name: thomtoogood.beetbox-backdrop }
  - { name: thomtoogood.beetbox-cakephp }
  - { name: thomtoogood.beetbox-concrete5 }
  - { name: thomtoogood.beetbox-kohana }
  - { name: thomtoogood.beetbox-modx }
  - { name: thomtoogood.beetbox-silverstripe }
  - { name: thomtoogood.beetbox-slim }
  - { name: thomtoogood.beetbox-wordpress }

# Symlinks.
symlinks: no

# Known hosts.
known_hosts: no

# Apache config.
apache_daemon: apache2
apache_vhosts:
  - servername: "{{ beet_domain }}"
    documentroot: "{{ beet_web }}"
apache_mods_enabled:
  - authn_core.load
  - expires.load
  - ssl.load
  - rewrite.load

# Databases.
mysql_databases:
  - name: "{{ beet_mysql_database }}"
    encoding: utf8
    collation: utf8_general_ci
mysql_users:
  - name: "{{ beet_mysql_user }}"
    host: "%"
    password: "{{ beet_mysql_password }}"
    priv: "{{ beet_mysql_database }}.*:ALL"

# Extra utilities form provided roles.
# Comment out the ones that do not need to be installed.
installed_extras:
  - adminer
  - mailhog
  - memcached
  - xdebug
  # - xhprof
  - selenium
  - drupal-console
  # - varnish
  # - pimpmylog
  # - nginx
  # - nodejs
  # - ruby
  # - solr
  # - redis

# Extra packages.
extra_packages:
  - imagemagick
  - unzip

# Firewall config.
firewall_allowed_tcp_ports:
  - "22"
  - "25"
  - "80"
  - "81"
  - "443"
  - "4444"
  - "8025"
  - "8080"
  - "8443"
  - "8983"
firewall_allowed_udp_ports:
  - "5353"
firewall_log_dropped_packets: false

# git config.
git_packages:
  - git

# Varnish config.
varnish_listen_port: 81
varnish_storage: "malloc,256m"

# Nodejs config.
nodejs_version: "0.12"
nodejs_npm_global_packages: []

# Ruby config.
ruby_install_gems_user: "vagrant"
ruby_install_gems: []

# Apache config.
apache_remove_default_vhost: true
apache_listen_port: 80
apache_vhosts:
  - servername: "beetbox.local"
    documentroot: "/drupal"

# Nginx config.
nginx_php_fpm: /var/run/php5-fpm.sock

# PHP config.
php_version: "5.6"
php_memory_limit: "192M"
php_date_timezone: "Australia/Melbourne"
php_display_errors: "On"
php_display_startup_errors: "On"
php_enable_php_fpm: 1
php_realpath_cache_size: "1024K"
php_sendmail_path: "/usr/sbin/ssmtp -t"
php_opcache_enabled_in_ini: true
php_opcache_memory_consumption: "192"
php_opcache_max_accelerated_files: 4096
php_max_input_vars: "4000"
php_packages:
  - php5
  - libapache2-mod-php5
  - php5-mcrypt
  - php5-cli
  - php5-common
  - php5-curl
  - php5-dev
  - php5-fpm
  - php5-gd
  - php5-intl
  - php-pear
  - php-apc
  - libpcre3-dev

# Composer config.
composer_path: /usr/bin/composer
composer_home_path: '/home/vagrant/.composer'
composer_home_owner: vagrant
composer_home_group: vagrant
# Composer global packages.
# composer_global_packages:
#   - { name: phpunit/phpunit, release: '@stable' }

# Drush config.
drush_version: "8.0.2"
drush_keep_updated: "{{ (drush_version != '8.0.2') }}"
drush_composer_cli_options: "--prefer-dist --no-interaction"

# MySQL config.
mysql_root_password: ""
mysql_slow_query_log_enabled: true
mysql_slow_query_time: 2
mysql_wait_timeout: 300
adminer_install_filename: index.php

# XDebug config.
php_xdebug_default_enable: 1
php_xdebug_coverage_enable: 1
php_xdebug_cli_enable: 0
php_xdebug_remote_enable: 1
php_xdebug_remote_connect_back: 1
php_xdebug_max_nesting_level: 256
# IDE key for debug.
php_xdebug_idekey: PHPSTORM
# php_xdebug_idekey: sublime.xdebug

# Solr config.
solr_version: "4.10.4"
solr_xms: "64M"
solr_xmx: "128M"

# Selenium config.
selenium_version: 2.46.0

# Other config.
known_hosts_path: ~/.ssh/known_hosts
