---
- name: Ensure symlink dest is empty.
  file:
    path: "{{ item.link }}"
    state: absent
  when: "{{ item.force | default('false') }}"
  with_items: "{{ symlinks }}"

- name: Create symlinks.
  file:
    src: "{{ item.src }}"
    dest: "{{ item.link }}"
    state: link
  with_items: "{{ symlinks }}"
